---
title: "hw3 logitstic"
author: "Ballesteros"
date: "2023-03-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## loading libraries
```{r}
library(class)
library(caret)
library(ggplot2)
library(gmodels)
library(neuralnet)
library(glmnet)
library(stringr)
```

## Downloading and Prepping the Data

```{r}
#Downloading and Prepping the Data
tele <- read.csv("tele.csv", stringsAsFactors = TRUE)
summary(tele)

#We are deleting the "duration" variable because it is an after the fact measurement. We only should be using variables that we know before the call
tele$duration <- NULL

# Deleting the column X
tele$X <- NULL

# Changing pdays to a dummy and deleting pdays
tele$pdaysdummy <- ifelse(tele$pdays == 999, 0, 1)
tele$pdays <- NULL

str(tele)
```

## Getting Data Ready for Analysis

```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

telemm <- as.data.frame(model.matrix(~.-1,tele))

# Randomize the rows in the data (shuffling the rows)
set.seed(12345)
tele_random <- telemm[sample(nrow(telemm)),]

#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything 
tele_norm <- as.data.frame(lapply(tele_random, normalize))

saveRDS(tele_norm, file = "tele_norm")
```

## Getting Train and Test Samples

```{r}
set.seed(12345)
test_set <- sample(1:nrow(tele_norm), nrow(tele_norm)/2) 

tele_train <- tele_norm[-test_set,]
tele_test  <- tele_norm[test_set,]

saveRDS(tele_train,"tele_train")
saveRDS(tele_test,"tele_test")
```

